import { defineConfig } from "oxfmt";

export default defineConfig({
  printWidth: 80,
  attributePosition: "auto",
  bracketSameLine: false,
  bracketSpacing: true,
  enabled: true,
  expand: "auto",
  formatWithErrors: true,
  indentStyle: "space",
  indentWidth: 2,
  lineEnding: "crlf",
  lineWidth: 80,
  useEditorconfig: true,
  insertFinalNewline: false,
  arrowParens: "always",
  jsxSingleQuote: false,
  quoteProps: "as-needed",
  singleQuote: false,
  semi: true,
  trailingComma: "es5",
  sortTailwindcss: true,
  ignorePatterns: [
    ".skills",
    "seed",
    "*.md",
    ".github",
    ".versionrc.json",
    ".commitlintrc.json",
    "pnpm-workspace.yaml",
  ],
  sortImports: {
    enabled: true,
    newlinesBetween: false,
    customGroups: [
      {
        groupName: "react",
        elementNamePattern: ["react"],
      },
      {
        groupName: "next",
        elementNamePattern: ["next", "next/**"],
      },
      {
        groupName: "lucide-react",
        elementNamePattern: ["lucide-react"],
      },
      {
        groupName: "entities",
        elementNamePattern: ["~/entities", "~/entities/**"],
      },
      {
        groupName: "features",
        elementNamePattern: ["~/features", "~/features/**"],
      },
      { groupName: "shared", elementNamePattern: ["~/shared", "~/shared/**"] },
      { groupName: "views", elementNamePattern: ["~/views", "~/views/**"] },
      {
        groupName: "widgets",
        elementNamePattern: ["~/widgets", "~/widgets/**"],
      },
      { groupName: "alias-rest", elementNamePattern: ["~/**"] },
    ],
    groups: [
      "type-builtin",
      "type-import",
      "type-internal",
      { newlinesBetween: true },
      "react",
      "next",
      "lucide-react",
      { newlinesBetween: true },
      "value-builtin",
      "value-external",
      { newlinesBetween: true },
      "entities",
      { newlinesBetween: true },
      "features",
      { newlinesBetween: true },
      "shared",
      { newlinesBetween: true },
      "views",
      { newlinesBetween: true },
      "widgets",
      { newlinesBetween: true },
      "alias-rest",
      { newlinesBetween: true },
      ["value-parent", "value-sibling", "value-index"],
      "unknown",
    ],
  },
});